### ISSUE TITLE
GET /api/user/:username does not require authentication

### ISSUE THREAD

**Issue by stanleyrya** [molecular-playground/ms-users#13]
We need to require authentication for this kind of route. Don't forget to fix the gateway as well!

**Comment by alechirsch** [comment]
It should likey not even exist, I do not see a use case for this specific route. It also returns the hashed password...

**Comment by stanleyrya** [comment]
:+1:

**Comment by stanleyrya** [comment]
I'm working on testing v0.4.0 but after I may take a look into this

**Comment by ethanfine** [comment]
Route was removed from gateway. Its useful to leave it in ms users for testing, and it is no longer exposed to the client.
