### ISSUE TITLE
Create User Pulls Location From Query and Body

### ISSUE THREAD

**Issue by stanleyrya** [molecular-playground/ms-users#2]
[This line](https://github.com/molecular-playground/ms-users/blob/c4ee5d288e4ff5a704ef7c93b456b0a02d2a32e4/routes/users.js#L42) is wrong!

**Comment by akaplo** [comment]
Fixed [here](https://github.com/molecular-playground/ms-users/commit/4352be6be58cd22220adc813194efb29904363b4#diff-7628e6ddd9de1f212493d044a6ba105dR40)
