### ISSUE TITLE
Error reporting on bad login cridentials

### ISSUE THREAD

**Issue by GaryPWhite** [molecular-playground/ms-users#9]
I'm noticing that when there is an invalid user/email I'm returned 200 with a message inside. an error status code would be more useful for the use cases of returning this information. 417 Expectation Failed or 400 Bad Request with a verbose message I think would do perfectly. Thanks guys!

**Comment by alechirsch** [comment]
Which call specifically?

**Comment by GaryPWhite** [comment]
login credentials ^^ logging in

**Comment by GaryPWhite** [comment]
but just in general, getting an error for a bad request, improper parameters, anything like that, would be easier to handle on my end because we can use a different callback for it instead of handling it all in the same function. Plus it prints to the console automatically.

**Comment by alechirsch** [comment]
Yeah, I thought we fixed all of those issues. We seem to have missed some.

**Comment by GaryPWhite** [comment]
:+1:

**Comment by alechirsch** [comment]
All of the error handling is fixed and will be pushed to the server later tonight (hopefully).

**Comment by stanleyrya** [comment]
Pushed! Let's hope it works :laughing:
